### ISSUE TITLE
hash from copy is not hash for asset injection

### ISSUE THREAD

**Issue by moderndeveloperllc** [jharris4/html-webpack-deploy-plugin#1]
If you use `copy` and inject a hash there, it's not the same as generated via the `hash (assetName, hash)` option. `copy` is using `crypto.createHash('md4').update(content).digest('hex');` and `hash` is using the webpack compile hash - totally different.

I would very much like to use the content hash as _some_ of my helpers don't change for several builds and I don't want to bust caching for them if the MD4 doesn't change. `assetName` doesn't point to a file as it hasn't been copied over by this point in time. Might it be possible to get the `from` path into the function so I can load the file and get the content hash myself?

```
const OUTPUT_PATH = ENV === 'production' ? resolve('dist') : resolve('src');
const helpers = [
  {
    from: resolve('./src/vendor/*.js'),
    to: join(OUTPUT_PATH, 'vendor', '[name].[contenthash:8].[ext]'),
    flatten: true,
  },
];
new HtmlWebpackPlugin(),
new HtmlWebpackDeployPlugin({
    assets: {
      copy: [...helpers],
        scripts: [
          {
            append: false,
            path: './vendor/regenerator-runtime.min.js',
            attributes: {noModule: true},
          },
          {
            append: false,
            path: './vendor/babel-helpers.min.js',
            attributes: {noModule: true},
          },
          {
            append: false,
            path: './vendor/babel-helpers-modern.min.js',
            attributes: {type: 'module'},
          },
          {
            append: false,
            path: './vendor/webcomponents-loader.js',
            attributes: {type: 'module'},
          }],
      },
      useAssetsPath: false,
      usePublicPath: false,
      hash: (assetName, hash) => {
        // const contentHash = crypto.createHash('md4').update(fs.readFileSync(assetName, 'utf8')).digest('hex');
        assetName = assetName.replace(/\.js$/, '.' + hash + '.js');
        return assetName;
      },
    }),
```

**Comment by jharris4** [comment]
Hi, I have looked into feeding `copy-webpack-plugin` into `html-webpack-plugin` in the past, but the problem is that the former gets applied after the latter (last I checked anyway).

That's the reason why I added the `glob` option to `html-webpack-tags-plugin`, as a way to be able to inject assets even if they have not yet been copied to webpack's output directory by the time the html plugin generates the html tags.

My suggestion would be to take `assetName` and use it to reverse engineer the `copy.from`.

For example with your above example, this might look something like:

```
const copyFrom = assetName.replace(join(OUTPUT_PATH, 'vendor'), './src/vendor');
const contentHash = crypto.createHash('md4').update(fs.readFileSync(copyFrom, 'utf8')).digest('hex');
```

You'd also probably need to remove the `[contenthash:8]` from the `copy.to` for this to work.

I know it's not ideal, but I can't of anything else given the limitations of the 2 plugins that this plugin is built on top of. I'm all ears though if you have suggestions/ideas for how to work around this (and a PR would be welcome as well! ;-) )

Also, it looks like you're using this plugin to copy assets from vendor packages and insert those into your html. That is actually the reason I built this plugin (on top of the more generic tags plugin), but I'm using the package version instead of content hashes.

Maybe this would be an option for you as well?

Something along the lines of:

```
new HtmlWebpackDeployPlugin({
  packages: {
    '@babel/helpers': {
      copy: {
        from: 'lib/helpers.js',
        to: '[name].[ext]',
      },
      scripts: {
        path: 'helpers.js'
      }
    }
  }
});
```

This would then inject the script as something like: `<script src="@babel/helpers-7.0.45/helper.js"/>`. Note that the package version is automatically added, which for my use cases is better/simpler than using a hash.

**Comment by moderndeveloperllc** [comment]
@jharris4 Thanks for the direction. I will look into the `assetName` fix. FWIW, the `babel-helpers` file I'm using is a concatenation of lots of the helpers as this project is for polymer/let-element web-components. I snipped out where I'm using `packages` to pull files from `@webcomponents/webcomponentsjs`. It's a really nice plugin btw!

**Comment by jharris4** [comment]
Ok, let me know how it turns out!

Also I’m glad you’re making use of the `packages` option, and thanks for the positive feedback 😉

**Comment by moderndeveloperllc** [comment]
@jharris4 Had another project come up, so it's taken some time. I put the final (yeh, right) version up as a [gist](https://gist.github.com/moderndeveloperllc/a3774d2890fcff56d7b39b9883b0879f). Your plugin code starts around line 182. FYI, this is for a LitElement/Polymer frontend with a module/nomodule build split based off of [this project](https://github.com/web-padawan/polymer3-webpack-starter/blob/master/webpack.config.js).

**Comment by jharris4** [comment]
Nice, looks like you got the content hash working then! 😉
